version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: url-shortener-db
    environment:
      - POSTGRES_USER=@@@@@@@@
      - POSTGRES_PASSWORD=@@@@@@@@
      - POSTGRES_DB=urldb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U @@@@@@@@ -d urldb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/urldb
      - SPRING_DATASOURCE_USERNAME=@@@@@@@@
      - SPRING_DATASOURCE_PASSWORD=@@@@@@@@
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      postgres-db:
        condition: service_healthy # Waits for DB to be healthy
      redis-cache:
        condition: service_started

